name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - run: yarn
      - run: chmod +x ./bin/run
      - run: yarn test:ci
      - run: yarn codecov
